import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "background": "#fcf8ff",
        "on-surface-variant": "#49454e",
        "on-primary-container": "#564475",
        "surface-tint": "#695587",
        "on-secondary-fixed-variant": "#1e4a69",
        "on-secondary-fixed": "#001e31",
        "primary-container": "#cbb4ed",
        "tertiary-container": "#c8c074",
        "outline-variant": "#cbc4cf",
        "primary": "#695587",
        "inverse-on-surface": "#f2efff",
        "tertiary": "#66601e",
        "surface": "#fcf8ff",
        "inverse-primary": "#d4bcf6",
        "on-surface": "#1a1a2e",
        "secondary-fixed": "#cce5ff",
        "on-primary-fixed-variant": "#503e6e",
        "secondary-container": "#b0d9fe",
        "primary-fixed-dim": "#d4bcf6",
        "secondary-fixed-dim": "#a2cbf0",
        "surface-dim": "#dad7f3",
        "on-secondary-container": "#365f7f",
        "surface-container-low": "#f5f2ff",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#ecdcff",
        "on-tertiary-container": "#534e0d",
        "error-container": "#ffdad6",
        "inverse-surface": "#2f2e43",
        "outline": "#7b757f",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#4d4806",
        "secondary": "#396282",
        "surface-bright": "#fcf8ff",
        "tertiary-fixed-dim": "#d1c97c",
        "on-background": "#1a1a2e",
        "on-tertiary-fixed": "#1f1c00",
        "surface-container-highest": "#e2e0fc",
        "surface-variant": "#e2e0fc",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#e8e5ff",
        "surface-container": "#efecff",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#eee595",
        "error": "#ba1a1a",
        "on-primary-fixed": "#231140",
        "warning": "#e3a008",
        "success": "#22c55e"
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "-apple-system", "sans-serif"],
        "headline-md": ["Inter"],
        "label-md": ["Inter"],
        "body-md": ["Inter"],
        "label-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-xl": ["Inter"],
        "body-sm": ["Inter"],
        "headline-sm": ["Inter"],
        "body-lg": ["Inter"]
      },
      keyframes: {
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "slide-up": {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "pulse-soft": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.7" },
        },
      },
      animation: {
        "fade-in": "fade-in 0.5s ease-out forwards",
        "slide-up": "slide-up 0.5s ease-out forwards",
        "pulse-soft": "pulse-soft 2s ease-in-out infinite",
      },
      borderRadius: {
        xl: "1rem",
        "2xl": "1.5rem",
      },
      boxShadow: {
        soft: "0 2px 15px -3px rgba(0, 0, 0, 0.07), 0 10px 20px -2px rgba(0, 0, 0, 0.04)",
        glow: "0 0 20px rgba(203, 180, 237, 0.3)",
      },
    },
  },
  plugins: [],
};

export default config;
